# Generated by Django 3.0 on 2019-12-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('m1', models.CharField(max_length=100)),
                ('m2', models.CharField(max_length=100)),
                ('m3', models.CharField(max_length=100)),
            ],
        ),
    ]
